### ISSUE TITLE
OS/Architecture for Arm64

### ISSUE THREAD

**Issue by engageub** [simeononsecurity/docker-mesonnetwork#1]
Hi,
With respect to the docker image, the OS architecture for arm64 shows amd64.
Could you please look into it and let me know if it would work for arm64 architecture.
Please find the screenshot below.

![image](https://github.com/simeononsecurity/docker-mesonnetwork/assets/103608400/e2d591e5-0c40-4150-8b5b-0e6da072a3df)

Thank you

**Comment by simeononsecurity** [comment]
Yeah there were some changes on how to specify the architecture recently that my automatons didn't capture. 
This one also had an error in the build command. You should know this isn't an image we plan on actively maintaining. But it can be used as a stepping stone for the mesonnetwork devs to get going if they would like to offer docker support in the future.

Should be fixed in https://github.com/simeononsecurity/docker-mesonnetwork/blob/main/.github/workflows/docker-image-arm64.yml


Alternatively you can always build it yourself on the arm device you have with

`docker build -t mesonnetwork -f Dockerfile.arm64 .`

**Comment by engageub** [comment]
Thank you for the response and update. I am aware that this is unofficial version but would like to add it in my script. So raised an issue to check if it would be compatible.  Thank you for making changes and updating the docker image.
